title: Notas do Rafa
tagline: Ficção & crônica
description: Textos de Rafa Mass
url: "https://rfmss.github.io"
baseurl: "/nota"

lang: pt-BR
timezone: America/Sao_Paulo

author:
  name: Rafa Mass

permalink: /posts/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Rafa Mass

exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - tools
  - docs
  - LICENSE
  - "*.config.js"
  - "package*.json"
